//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{

    [Persistent(@"Ben")]
    public partial class Ben1 : XPObject
    {
        string fRecID;
        [Indexed(@"GCRecord;OptimisticLockField", Name = @"Index1", Unique = true)]
        public string RecID
        {
            get { return fRecID; }
            set { SetPropertyValue<string>("RecID", ref fRecID, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
    }

}
