//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{

    public partial class MFISBAS : XPLiteObject
    {
        int fIDNO;
        [Key]
        public int IDNO
        {
            get { return fIDNO; }
            set { SetPropertyValue<int>("IDNO", ref fIDNO, value); }
        }
        string fKEYSTR;
        [Indexed(Name = @"UQ__MFISBAS__3E462A7CEC6BD63C", Unique = true)]
        [Size(10)]
        public string KEYSTR
        {
            get { return fKEYSTR; }
            set { SetPropertyValue<string>("KEYSTR", ref fKEYSTR, value); }
        }
        DateTime fFISTARIH;
        [Indexed(Name = @"MFB_KEYTARIH")]
        public DateTime FISTARIH
        {
            get { return fFISTARIH; }
            set { SetPropertyValue<DateTime>("FISTARIH", ref fFISTARIH, value); }
        }
        int fFISNO;
        public int FISNO
        {
            get { return fFISNO; }
            set { SetPropertyValue<int>("FISNO", ref fFISNO, value); }
        }
        string fFISACIKLAMA;
        [Size(60)]
        public string FISACIKLAMA
        {
            get { return fFISACIKLAMA; }
            set { SetPropertyValue<string>("FISACIKLAMA", ref fFISACIKLAMA, value); }
        }
        char fFISTURU;
        public char FISTURU
        {
            get { return fFISTURU; }
            set { SetPropertyValue<char>("FISTURU", ref fFISTURU, value); }
        }
        string fFISNTLK;
        [Size(3)]
        public string FISNTLK
        {
            get { return fFISNTLK; }
            set { SetPropertyValue<string>("FISNTLK", ref fFISNTLK, value); }
        }
        decimal fBTOPLAM;
        public decimal BTOPLAM
        {
            get { return fBTOPLAM; }
            set { SetPropertyValue<decimal>("BTOPLAM", ref fBTOPLAM, value); }
        }
        decimal fATOPLAM;
        public decimal ATOPLAM
        {
            get { return fATOPLAM; }
            set { SetPropertyValue<decimal>("ATOPLAM", ref fATOPLAM, value); }
        }
        int fYEVMIYENO;
        public int YEVMIYENO
        {
            get { return fYEVMIYENO; }
            set { SetPropertyValue<int>("YEVMIYENO", ref fYEVMIYENO, value); }
        }
        int fENTEGRENO;
        public int ENTEGRENO
        {
            get { return fENTEGRENO; }
            set { SetPropertyValue<int>("ENTEGRENO", ref fENTEGRENO, value); }
        }
        short fFISKAPA;
        public short FISKAPA
        {
            get { return fFISKAPA; }
            set { SetPropertyValue<short>("FISKAPA", ref fFISKAPA, value); }
        }
        string fKPERSONEL;
        [Size(30)]
        public string KPERSONEL
        {
            get { return fKPERSONEL; }
            set { SetPropertyValue<string>("KPERSONEL", ref fKPERSONEL, value); }
        }
        DateTime fKTARIHI;
        public DateTime KTARIHI
        {
            get { return fKTARIHI; }
            set { SetPropertyValue<DateTime>("KTARIHI", ref fKTARIHI, value); }
        }
    }

}
