//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{

    public partial class MFISDET : XPLiteObject
    {
        string fHESAPKODU;
        [Indexed(Name = @"MFD_KYHSKOD")]
        [Size(18)]
        public string HESAPKODU
        {
            get { return fHESAPKODU; }
            set { SetPropertyValue<string>("HESAPKODU", ref fHESAPKODU, value); }
        }
        string fFISACIKLAMA;
        [Size(50)]
        public string FISACIKLAMA
        {
            get { return fFISACIKLAMA; }
            set { SetPropertyValue<string>("FISACIKLAMA", ref fFISACIKLAMA, value); }
        }
        decimal fTLBORC;
        public decimal TLBORC
        {
            get { return fTLBORC; }
            set { SetPropertyValue<decimal>("TLBORC", ref fTLBORC, value); }
        }
        decimal fTLALACAK;
        public decimal TLALACAK
        {
            get { return fTLALACAK; }
            set { SetPropertyValue<decimal>("TLALACAK", ref fTLALACAK, value); }
        }
        decimal fALTBIRIMBORC;
        public decimal ALTBIRIMBORC
        {
            get { return fALTBIRIMBORC; }
            set { SetPropertyValue<decimal>("ALTBIRIMBORC", ref fALTBIRIMBORC, value); }
        }
        decimal fALTBIRIMALACAK;
        public decimal ALTBIRIMALACAK
        {
            get { return fALTBIRIMALACAK; }
            set { SetPropertyValue<decimal>("ALTBIRIMALACAK", ref fALTBIRIMALACAK, value); }
        }
        decimal fDOVIZBORC;
        public decimal DOVIZBORC
        {
            get { return fDOVIZBORC; }
            set { SetPropertyValue<decimal>("DOVIZBORC", ref fDOVIZBORC, value); }
        }
        decimal fDOVIZALACAK;
        public decimal DOVIZALACAK
        {
            get { return fDOVIZALACAK; }
            set { SetPropertyValue<decimal>("DOVIZALACAK", ref fDOVIZALACAK, value); }
        }
        char fBORCALACAK;
        public char BORCALACAK
        {
            get { return fBORCALACAK; }
            set { SetPropertyValue<char>("BORCALACAK", ref fBORCALACAK, value); }
        }
        string fBELGETIPI;
        [Size(20)]
        public string BELGETIPI
        {
            get { return fBELGETIPI; }
            set { SetPropertyValue<string>("BELGETIPI", ref fBELGETIPI, value); }
        }
        string fBELGENO;
        [Size(20)]
        public string BELGENO
        {
            get { return fBELGENO; }
            set { SetPropertyValue<string>("BELGENO", ref fBELGENO, value); }
        }
        DateTime fBELGETARIHI;
        public DateTime BELGETARIHI
        {
            get { return fBELGETARIHI; }
            set { SetPropertyValue<DateTime>("BELGETARIHI", ref fBELGETARIHI, value); }
        }
        string fBELGEACIKLAMASI;
        [Size(50)]
        public string BELGEACIKLAMASI
        {
            get { return fBELGEACIKLAMASI; }
            set { SetPropertyValue<string>("BELGEACIKLAMASI", ref fBELGEACIKLAMASI, value); }
        }
        string fKPERSONEL;
        [Size(30)]
        public string KPERSONEL
        {
            get { return fKPERSONEL; }
            set { SetPropertyValue<string>("KPERSONEL", ref fKPERSONEL, value); }
        }
        DateTime fKTARIHI;
        public DateTime KTARIHI
        {
            get { return fKTARIHI; }
            set { SetPropertyValue<DateTime>("KTARIHI", ref fKTARIHI, value); }
        }
        string fBELGEACIKLAMASI2;
        [Size(20)]
        public string BELGEACIKLAMASI2
        {
            get { return fBELGEACIKLAMASI2; }
            set { SetPropertyValue<string>("BELGEACIKLAMASI2", ref fBELGEACIKLAMASI2, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("IDNO")]
            public int IDNO { get; set; }
            [Persistent("DETAYIDNO")]
            public int DETAYIDNO { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
