//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecSP_C5IDNOAL(Session session, string Tur, string IP, string KL, string GIDNO)
        {
            return session.ExecuteSproc("SP_C5IDNOAL", new OperandValue(Tur), new OperandValue(IP), new OperandValue(KL), new OperandValue(GIDNO));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecSP_CONVERTYAP(Session session, string Sql)
        {
            return session.ExecuteSproc("SP_CONVERTYAP", new OperandValue(Sql));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecSP_IDNOAL(Session session, string Tur, string IP, string KL)
        {
            return session.ExecuteSproc("SP_IDNOAL", new OperandValue(Tur), new OperandValue(IP), new OperandValue(KL));
        }
    }
}
