//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{

    [NonPersistent]
    public partial class TNMSZMUHASEBEKODU : XPLiteObject
    {
        int fIDNO;
        public int IDNO
        {
            get { return fIDNO; }
            set { SetPropertyValue<int>("IDNO", ref fIDNO, value); }
        }
        string fHESAPKODU;
        [Size(18)]
        public string HESAPKODU
        {
            get { return fHESAPKODU; }
            set { SetPropertyValue<string>("HESAPKODU", ref fHESAPKODU, value); }
        }
        DateTime fFISTARIH;
        public DateTime FISTARIH
        {
            get { return fFISTARIH; }
            set { SetPropertyValue<DateTime>("FISTARIH", ref fFISTARIH, value); }
        }
        int fFISNO;
        public int FISNO
        {
            get { return fFISNO; }
            set { SetPropertyValue<int>("FISNO", ref fFISNO, value); }
        }
        string fFISNTLK;
        [Size(3)]
        public string FISNTLK
        {
            get { return fFISNTLK; }
            set { SetPropertyValue<string>("FISNTLK", ref fFISNTLK, value); }
        }
        string fFISACIKLAMA;
        [Size(60)]
        public string FISACIKLAMA
        {
            get { return fFISACIKLAMA; }
            set { SetPropertyValue<string>("FISACIKLAMA", ref fFISACIKLAMA, value); }
        }
    }

}
