//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace testXaf001.Module.BusinessObjects.Muhasebe
{

    public partial class ZDATLST : XPLiteObject
    {
        string fACK;
        [Size(60)]
        public string ACK
        {
            get { return fACK; }
            set { SetPropertyValue<string>("ACK", ref fACK, value); }
        }
        string fCINS;
        [Size(20)]
        public string CINS
        {
            get { return fCINS; }
            set { SetPropertyValue<string>("CINS", ref fCINS, value); }
        }
        short fUZUNLUK;
        public short UZUNLUK
        {
            get { return fUZUNLUK; }
            set { SetPropertyValue<short>("UZUNLUK", ref fUZUNLUK, value); }
        }
        short fNO;
        public short NO
        {
            get { return fNO; }
            set { SetPropertyValue<short>("NO", ref fNO, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(5)]
            [Persistent("KOD")]
            public string KOD { get; set; }
            [Size(60)]
            [Persistent("AD")]
            public string AD { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
